# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HttpsignatureProxy < Formula
  desc "Localhost HTTP Signatures proxy."
  homepage "https://github.com/upvestco/httpsignature-proxy"
  version "1.3.2"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upvestco/httpsignature-proxy/releases/download/v1.3.2/httpsignature-proxy_v1.3.2_macOS_64-bit.tar.gz"
      sha256 "41f0548b0f5471cda557a959c728733e2447df0b0bebd09aaef371c7e40260cd"

      def install
        bin.install "httpsignature-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upvestco/httpsignature-proxy/releases/download/v1.3.2/httpsignature-proxy_v1.3.2_macOS_arm64.tar.gz"
      sha256 "ff829473b127f78a213f1e8893619283808dd615b906056c634fadf84d616db5"

      def install
        bin.install "httpsignature-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/upvestco/httpsignature-proxy/releases/download/v1.3.2/httpsignature-proxy_v1.3.2_Linux_arm64.tar.gz"
      sha256 "a69363012a4e7f8440aafc26fecb71dd999cc9767f9d4079e7994f616b77bef4"

      def install
        bin.install "httpsignature-proxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/upvestco/httpsignature-proxy/releases/download/v1.3.2/httpsignature-proxy_v1.3.2_Linux_64-bit.tar.gz"
      sha256 "8b858ab7f995bdbf48579c6cf09ae7386175f9a458bc247a128ca0e030553098"

      def install
        bin.install "httpsignature-proxy"
      end
    end
  end

  test do
    system "#{bin}/httpsignature-proxy version"
  end
end
