# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HttpsignatureProxy < Formula
  desc "Localhost HTTP Signatures proxy."
  homepage "https://github.com/upvestco/httpsignature-proxy"
  version "1.3.3"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/upvestco/httpsignature-proxy/releases/download/v1.3.3/httpsignature-proxy_v1.3.3_macOS_64-bit.tar.gz"
      sha256 "07cb7d18062e34cb4f3410a68a33251f4e90fcb8a80a72709b5c290d0e26d330"

      def install
        bin.install "httpsignature-proxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/upvestco/httpsignature-proxy/releases/download/v1.3.3/httpsignature-proxy_v1.3.3_macOS_arm64.tar.gz"
      sha256 "91ba843605ed3928f1d25e276d0549ae3c8d59807b95aba91cef5a8e508bdb7a"

      def install
        bin.install "httpsignature-proxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/upvestco/httpsignature-proxy/releases/download/v1.3.3/httpsignature-proxy_v1.3.3_Linux_64-bit.tar.gz"
      sha256 "1160cbdd99cea69aa2aca81940faa95fb5638f02a495611baeb7b2657ba50e12"

      def install
        bin.install "httpsignature-proxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/upvestco/httpsignature-proxy/releases/download/v1.3.3/httpsignature-proxy_v1.3.3_Linux_arm64.tar.gz"
      sha256 "7be9fd49b93d83840157c60734e75388ca0dc91cd855ab462f771be91dc955b7"

      def install
        bin.install "httpsignature-proxy"
      end
    end
  end

  test do
    system "#{bin}/httpsignature-proxy version"
  end
end
